services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:dev
    working_dir: /var/www
    user: "1000:1000"  # Utilise l'UID/GID de l'utilisateur hôte
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www:ro
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data_dev:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data_dev:
  redis_data_dev:
  node_modules:

networks:
  app-network:
    driver: bridge
